language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - pip install redis --use-mirrors || echo "ok"
# command to run tests
script:
  - python setup.py test
  - python setup.py install
  - python examples/dirq_simple.py
  - python examples/dirqset_simple.py
