notifications:
  email:
    - mig-travis@cern.ch
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - pip install pep8 --use-mirrors
# command to run tests
script:
  - pep8 examples/ dirq/ test/
  - python setup.py test
  - python setup.py install
  - python examples/dirq_simple.py
  - python examples/dirqset_simple.py
